export const asmGrdMap: Record<string, string> = {
  asmGrd01: "급성질환 - 급성기뇌졸증",
  asmGrd02: "급성심근경색 평가",
  asmGrd03: "만성질환 - 혈액투석",
  asmGrd04: "정신 건강 - 의료급여정신과",
  asmGrd05: "약제 - 수술적 예방적 항생제",
  asmGrd06: "급성질환 - 급성신근경색",
  asmGrd07: "약제 - 급성상기도 감염 항생제 처방률",
  asmGrd08: "약제 - 주사제 처방률",
  asmGrd09: "약제 - 약품목수",
  asmGrd10: "요양병원 - 요양병원",
  asmGrd11: "정신건강외래영역 평가",
  asmGrd12: "암질환 - 대장암",
  asmGrd13: "암질환 - 위암",
  asmGrd14: "암질환 - 유방암",
  asmGrd15: "암질환 - 폐암",
  asmGrd16: "만성질환 - 천식",
  asmGrd17: "만성질환 - 만성폐쇄성폐질환",
  asmGrd18: "급성질환 - 폐렴",
  asmGrd19: "중환자실 - 성인 중환자실",
  asmGrd20: "중환자실 - 신생아 중환자실",
  asmGrd21: "마취",
  asmGrd22: "정신 건강 - 정신건강 입원 영역",
  asmGrd23: "만성질환 - 천식",
  asmGrd24: "만성질환 - 고혈압 당뇨병",
};