version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: hospin-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospin
      MYSQL_USER: user
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - hospin-network

  redis:
    image: redis:7
    container_name: hospin-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hospin-network

volumes:
  mariadb_data:
  redis_data:

networks:
  hospin-network:
    external: true