server:
  port: 8080

spring:
  application:
    name: HosPin

  profiles:
    active: dev

  config:
    import: optional:application-secret.yml

  jpa:
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    enable:
      jvm: true
      all: true
    distribution:
      percentiles:
        http.server.requests: 0.95, 0.5

firebaseAdminSdkPath: hospin-57573-firebase-adminsdk-fbsvc-04558e3b9d.json