spring:
  datasource:
    url: jdbc:mariadb://hospin-mariadb:3306/hospin
    username: user
    password: ${database.password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  ai:
    openai:
      api-key: ${openai.api-key}

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}