openapi:
  key:
    encoding: jEERY0I%2B1TH7S%2Bn8sIb%2BSG6YU19UHgWGYTvT5IOb7hEwO1JfgCdb%2BnB0RR19X7UBmzwy%2BuW35YSs%2FfKzxhUg6g%3D%3D
    decoding: jEERY0I+1TH7S+n8sIb+SG6YU19UHgWGYTvT5IOb7hEwO1JfgCdb+nB0RR19X7UBmzwy+uW35YSs/fKzxhUg6g==